/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nobre.caixa.celula;

import com.raven.table.TableCustom;
import com.raven.table.cell.TableCustomCell;
import com.raven.table.model.TableRowData;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.openswing.swing.client.EditButton;

/**
 *
 * @author User
 */
public class CelulaAcao extends TableCustomCell {

    /**
     * Creates new form CellAcao
     */
    public CelulaAcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butaoEdit = new com.nobre.caixa.swing.Button();
        butaoDelete = new com.nobre.caixa.swing.Button();

        butaoEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nobre/caixa/icon/edit.png"))); // NOI18N
        butaoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoEditActionPerformed(evt);
            }
        });

        butaoDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nobre/caixa/icon/delete.png"))); // NOI18N
        butaoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(butaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(butaoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butaoDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butaoEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butaoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoEditActionPerformed

    private void butaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nobre.caixa.swing.Button butaoDelete;
    private com.nobre.caixa.swing.Button butaoEdit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setData(Object o) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Object getData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public TableCustomCell createComponentCellEditor(TableCustom tc, TableRowData trd, Object o, int i, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void addEvent(TableCustom tabela, TableRowData data, int row) {
        butaoEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        
        
        });
    }

}
